# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "ast", ">=0"

gem "kpeg", "~>0.9", :group => [:development, :test]
gem "minitest", "~>5.4", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "guard", ">=0", :group => [:development, :test]
gem "guard-minitest", ">=0", :group => [:development, :test]
gem "guard-shell", ">=0", :group => [:development, :test]
gem "guard-rake", ">=0", :group => [:development, :test]
gem "rspec", ">=0", :group => [:development, :test]
gem "wdm", ">=0", :group => [:development, :test]
gem "hoe", "~>3.12", :group => [:development, :test]

# vim: syntax=ruby
